const Firebird = require('node-firebird');
const fs = require('fs');
const path = require('path');
const dbOptions = require('./dbConfig');

function inicializarBanco() {
    return new Promise((resolve, reject) => {
        const dbDir = path.dirname(dbOptions.database);
        if (!fs.existsSync(dbDir)) {
            fs.mkdirSync(dbDir, { recursive: true });
        }

        const downloadsDir = path.join(__dirname, 'downloads');
        if (!fs.existsSync(downloadsDir)) {
            fs.mkdirSync(downloadsDir, { recursive: true });
        }

        const dbExiste = fs.existsSync(dbOptions.database);

        if (!dbExiste) {
            console.log(`🔨 Banco de dados não encontrado em "${dbOptions.database}". Criando novo banco Firebird...`);
            Firebird.create(dbOptions, (err, db) => {
                if (err) {
                    console.error('❌ Erro ao criar o banco Firebird:', err);
                    return reject(err);
                }
                console.log('✅ Arquivo de banco de dados criado com sucesso!');
                executarDDLs(db, downloadsDir).then(resolve).catch(reject);
            });
        } else {
            console.log(`🔌 Banco de dados encontrado em "${dbOptions.database}". Conectando e verificando tabelas...`);
            Firebird.attach(dbOptions, (err, db) => {
                if (err) {
                    console.error('❌ Erro ao conectar no banco Firebird existente:', err);
                    return reject(err);
                }
                executarDDLs(db, downloadsDir).then(resolve).catch(reject);
            });
        }
    });
}

function executarDDLs(db, downloadsDir) {
    return new Promise((resolve, reject) => {
        const queries = [
            `CREATE TABLE TB_ASSUNTOS (
                ID_ASSUNTO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME VARCHAR(100) NOT NULL UNIQUE
            )`,
            `CREATE TABLE TB_CANAIS (
                ID_CANAL INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME_CANAL VARCHAR(150) NOT NULL,
                URL_YOUTUBE VARCHAR(255) NOT NULL UNIQUE,
                ATIVO SMALLINT DEFAULT 1
            )`,
            `CREATE TABLE TB_CANAL_ASSUNTO (
                ID_CANAL INTEGER NOT NULL,
                ID_ASSUNTO INTEGER NOT NULL,
                PALAVRA_CHAVE VARCHAR(100) NOT NULL,
                CONSTRAINT PK_CANAL_ASSUNTO PRIMARY KEY (ID_CANAL, ID_ASSUNTO),
                CONSTRAINT FK_VINCULO_CANAL FOREIGN KEY (ID_CANAL) REFERENCES TB_CANAIS (ID_CANAL) ON DELETE CASCADE,
                CONSTRAINT FK_VINCULO_ASSUNTO FOREIGN KEY (ID_ASSUNTO) REFERENCES TB_ASSUNTOS (ID_ASSUNTO) ON DELETE CASCADE
            )`,
            `CREATE TABLE TB_VIDEOS_BIBLIOTECA (
                ID_VIDEO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_CANAL INTEGER NOT NULL,
                ID_ASSUNTO INTEGER,
                TITULO_VIDEO VARCHAR(255) NOT NULL,
                URL_VIDEO VARCHAR(255) NOT NULL UNIQUE,
                THUMBNAIL_URL VARCHAR(500),
                STATUS_DOWNLOAD VARCHAR(20) DEFAULT 'PENDENTE',
                FORMATO_DOWNLOAD VARCHAR(10) DEFAULT 'MP4',
                CAMINHO_ARQUIVO VARCHAR(500),
                PROGRESSO INTEGER DEFAULT 0,
                DATA_PUBLICACAO TIMESTAMP,
                DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_VIDEO_CANAL FOREIGN KEY (ID_CANAL) REFERENCES TB_CANAIS (ID_CANAL)
            )`,
            `CREATE TABLE TB_CONFIGURACOES (
                ID_CONFIG INTEGER NOT NULL PRIMARY KEY,
                CAMINHO_DOWNLOADS VARCHAR(500),
                QTD_VIDEOS_BUSCA INTEGER DEFAULT 5,
                INTERVALO_MINUTOS INTEGER DEFAULT 60,
                DATA_INICIAL DATE,
                DATA_FINAL DATE,
                BUSCAR_VIDEOS SMALLINT DEFAULT 1,
                BUSCAR_SHORTS SMALLINT DEFAULT 1,
                BUSCAR_LIVES SMALLINT DEFAULT 1
            )`,
            // Migration: adiciona coluna FORMATO_DOWNLOAD ao banco existente (silenciado se já existir)
            `ALTER TABLE TB_VIDEOS_BIBLIOTECA ADD FORMATO_DOWNLOAD VARCHAR(10) DEFAULT 'MP4'`
        ];

        let index = 0;
        function rodarProximaQuery() {
            if (index >= queries.length) {
                // Insere ou garante configuracao inicial
                db.query('SELECT ID_CONFIG FROM TB_CONFIGURACOES WHERE ID_CONFIG = 1', (err, res) => {
                    if (!err && res && res.length === 0) {
                        const insertConfig = `
                            INSERT INTO TB_CONFIGURACOES (ID_CONFIG, CAMINHO_DOWNLOADS, QTD_VIDEOS_BUSCA, INTERVALO_MINUTOS, BUSCAR_VIDEOS, BUSCAR_SHORTS, BUSCAR_LIVES)
                            VALUES (1, ?, 5, 60, 1, 1, 1)
                        `;
                        db.query(insertConfig, [downloadsDir], (err) => {
                            if (err) console.error('⚠️ Erro ao criar configuracao inicial:', err);
                            else console.log('✅ Configuração inicial inserida com sucesso.');
                            db.detach();
                            resolve();
                        });
                    } else {
                        db.detach();
                        resolve();
                    }
                });
                return;
            }

            const q = queries[index];
            index++;
            // Usa querySilent pois erros "tabela já existe" são esperados e não devem logar avisos
            const queryFn = (db.querySilent || db.query).bind(db);
            queryFn(q, (err) => {
                if (err) {
                    const msg = err.message || '';
                    const isExistErr = msg.includes('already exists') || msg.includes('já existe');
                    if (!isExistErr) {
                        console.warn('⚠️ [init_db] Aviso DDL ignorado:', msg.split('\n')[0]);
                    }
                }
                rodarProximaQuery();
            });
        }

        rodarProximaQuery();
    });
}

if (require.main === module) {
    inicializarBanco()
        .then(() => {
            console.log('✨ Banco de dados inicializado e pronto para uso!');
            process.exit(0);
        })
        .catch((err) => {
            console.error('❌ Falha na inicialização do banco:', err);
            process.exit(1);
        });
}

module.exports = inicializarBanco;
