const Firebird = require('node-firebird');
const fs = require('fs');
const path = require('path');
const dbOptions = require('./dbConfig');

function inicializarBanco() {
    return new Promise((resolve, reject) => {
        const dbDir = path.dirname(dbOptions.database);
        if (!fs.existsSync(dbDir)) {
            fs.mkdirSync(dbDir, { recursive: true });
        }

        const downloadsDir = path.join(__dirname, 'downloads');
        if (!fs.existsSync(downloadsDir)) {
            fs.mkdirSync(downloadsDir, { recursive: true });
        }

        const dbExiste = fs.existsSync(dbOptions.database);

        if (!dbExiste) {
            console.log(`🔨 Banco de dados não encontrado em "${dbOptions.database}". Criando novo banco Firebird...`);
            Firebird.create(dbOptions, (err, db) => {
                if (err) {
                    console.error('❌ Erro ao criar o banco Firebird:', err);
                    return reject(err);
                }
                console.log('✅ Arquivo de banco de dados criado com sucesso!');
                executarDDLs(db, downloadsDir).then(resolve).catch(reject);
            });
        } else {
            console.log(`🔌 Banco de dados encontrado em "${dbOptions.database}". Conectando e verificando tabelas...`);
            Firebird.attach(dbOptions, (err, db) => {
                if (err) {
                    console.error('❌ Erro ao conectar no banco Firebird existente:', err);
                    return reject(err);
                }
                executarDDLs(db, downloadsDir).then(resolve).catch(reject);
            });
        }
    });
}

function executarDDLs(db, downloadsDir) {
    return new Promise((resolve, reject) => {
        const queries = [
            `CREATE TABLE TB_ASSUNTOS (
                ID_ASSUNTO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME VARCHAR(100) NOT NULL UNIQUE
            )`,
            `CREATE TABLE TB_CANAIS (
                ID_CANAL INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME_CANAL VARCHAR(150) NOT NULL,
                URL_YOUTUBE VARCHAR(255) NOT NULL UNIQUE,
                ATIVO SMALLINT DEFAULT 1
            )`,
            `CREATE TABLE TB_CANAL_ASSUNTO (
                ID_CANAL INTEGER NOT NULL,
                ID_ASSUNTO INTEGER NOT NULL,
                PALAVRA_CHAVE VARCHAR(100) NOT NULL,
                CONSTRAINT PK_CANAL_ASSUNTO PRIMARY KEY (ID_CANAL, ID_ASSUNTO),
                CONSTRAINT FK_VINCULO_CANAL FOREIGN KEY (ID_CANAL) REFERENCES TB_CANAIS (ID_CANAL) ON DELETE CASCADE,
                CONSTRAINT FK_VINCULO_ASSUNTO FOREIGN KEY (ID_ASSUNTO) REFERENCES TB_ASSUNTOS (ID_ASSUNTO) ON DELETE CASCADE
            )`,
            `CREATE TABLE TB_VIDEOS_BIBLIOTECA (
                ID_VIDEO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_CANAL INTEGER NOT NULL,
                ID_ASSUNTO INTEGER,
                TITULO_VIDEO VARCHAR(255) NOT NULL,
                URL_VIDEO VARCHAR(255) NOT NULL UNIQUE,
                THUMBNAIL_URL VARCHAR(500),
                STATUS_DOWNLOAD VARCHAR(20) DEFAULT 'PENDENTE',
                FORMATO_DOWNLOAD VARCHAR(10) DEFAULT 'MP4',
                CAMINHO_ARQUIVO VARCHAR(500),
                PROGRESSO INTEGER DEFAULT 0,
                DATA_PUBLICACAO TIMESTAMP,
                DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT FK_VIDEO_CANAL FOREIGN KEY (ID_CANAL) REFERENCES TB_CANAIS (ID_CANAL)
            )`,
            `CREATE TABLE TB_CONFIGURACOES (
                ID_CONFIG INTEGER NOT NULL PRIMARY KEY,
                CAMINHO_DOWNLOADS VARCHAR(500),
                QTD_VIDEOS_BUSCA INTEGER DEFAULT 5,
                INTERVALO_MINUTOS INTEGER DEFAULT 60,
                DATA_INICIAL DATE,
                DATA_FINAL DATE,
                BUSCAR_VIDEOS SMALLINT DEFAULT 1,
                BUSCAR_SHORTS SMALLINT DEFAULT 1,
                BUSCAR_LIVES SMALLINT DEFAULT 1,
                CHAVE_PIX VARCHAR(255),
                NOME_RECEBEDOR_PIX VARCHAR(150),
                CIDADE_RECEBEDOR_PIX VARCHAR(150)
            )`,
            `CREATE TABLE TB_PROMPTS_LOJA (
                ID_PROMPT INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TITULO VARCHAR(255) NOT NULL,
                CATEGORIA VARCHAR(100) DEFAULT 'GERAL',
                DESCRICAO_CURTA VARCHAR(500),
                PROMPT_SISTEMA BLOB SUB_TYPE TEXT,
                PRECO_REAIS NUMERIC(15,2) DEFAULT 9.90,
                TAGS VARCHAR(255),
                AUTOR VARCHAR(100) DEFAULT 'Connect Media AI',
                DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                ATIVO SMALLINT DEFAULT 1
            )`,
            `CREATE TABLE TB_VENDAS_PIX (
                ID_VENDA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                VALOR_TOTAL NUMERIC(15,2) NOT NULL,
                STATUS VARCHAR(20) DEFAULT 'PENDENTE',
                CODIGO_PIX VARCHAR(1000),
                DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                ITENS_JSON VARCHAR(2000)
            )`,
            `CREATE TABLE TB_MINHAS_COMPRAS (
                ID_COMPRA INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ID_PROMPT INTEGER NOT NULL,
                ID_VENDA INTEGER NOT NULL,
                DATA_COMPRA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE TB_USUARIOS (
                ID_USUARIO INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                NOME VARCHAR(150) NOT NULL,
                EMAIL VARCHAR(255) NOT NULL UNIQUE,
                SENHA_HASH VARCHAR(255) NOT NULL,
                PERFIL VARCHAR(20) DEFAULT 'CLIENTE',
                ATIVO SMALLINT DEFAULT 1,
                TOKEN_RECUPERACAO VARCHAR(255),
                DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )`,
            `CREATE TABLE TB_CONFIGURACOES_SAAS (
                ID_SAAS INTEGER PRIMARY KEY,
                CHAVE_PIX_MESTRE VARCHAR(255),
                NOME_RECEBEDOR VARCHAR(150),
                CIDADE_RECEBEDOR VARCHAR(150)
            )`,
            // Migrations silenciosas se colunas já existirem
            `ALTER TABLE TB_VIDEOS_BIBLIOTECA ADD FORMATO_DOWNLOAD VARCHAR(10) DEFAULT 'MP4'`,
            `ALTER TABLE TB_VIDEOS_BIBLIOTECA ADD ID_USUARIO INTEGER DEFAULT 1`,
            `ALTER TABLE TB_CANAIS ADD ID_USUARIO INTEGER DEFAULT 1`,
            `ALTER TABLE TB_VENDAS_PIX ADD ID_USUARIO INTEGER DEFAULT 1`,
            `ALTER TABLE TB_MINHAS_COMPRAS ADD ID_USUARIO INTEGER DEFAULT 1`,
            `ALTER TABLE TB_CONFIGURACOES ADD CHAVE_PIX VARCHAR(255)`,
            `ALTER TABLE TB_CONFIGURACOES ADD NOME_RECEBEDOR_PIX VARCHAR(150)`,
            `ALTER TABLE TB_CONFIGURACOES ADD CIDADE_RECEBEDOR_PIX VARCHAR(150)`,
            `ALTER TABLE TB_VENDAS_PIX ADD COMPROVANTE BLOB SUB_TYPE TEXT`
        ];

        let index = 0;
        function rodarProximaQuery() {
            if (index >= queries.length) {
                // Insere ou garante configuracao inicial
                db.query('SELECT ID_CONFIG FROM TB_CONFIGURACOES WHERE ID_CONFIG = 1', (err, res) => {
                    if (!err && res && res.length === 0) {
                        const insertConfig = `
                            INSERT INTO TB_CONFIGURACOES (ID_CONFIG, CAMINHO_DOWNLOADS, QTD_VIDEOS_BUSCA, INTERVALO_MINUTOS, BUSCAR_VIDEOS, BUSCAR_SHORTS, BUSCAR_LIVES, CHAVE_PIX, NOME_RECEBEDOR_PIX, CIDADE_RECEBEDOR_PIX)
                            VALUES (1, ?, 5, 60, 1, 1, 1, 'connectmedia@pix.com.br', 'Connect Media Solucoes', 'Sao Paulo')
                        `;
                        db.query(insertConfig, [downloadsDir], () => {
                            garantirUsuarioAdmin(db, () => populaPromptsIniciais(db, resolve));
                        });
                    } else {
                        garantirUsuarioAdmin(db, () => populaPromptsIniciais(db, resolve));
                    }
                });
                return;
            }

            const q = queries[index];
            index++;
            const queryFn = (db.querySilent || db.query).bind(db);
            queryFn(q, (err) => {
                rodarProximaQuery();
            });
        }

        rodarProximaQuery();
    });
}

function garantirUsuarioAdmin(db, callback) {
    const crypto = require('crypto');
    // Hash simples e robusto para senha admin123
    const senhaHashAdmin = crypto.createHash('sha256').update('admin123').digest('hex');

    db.query('SELECT FIRST 1 ID_USUARIO FROM TB_USUARIOS WHERE EMAIL = ?', ['admin@connectmedia.com.br'], (err, res) => {
        if (!err && res && res.length > 0) {
            return callback();
        }
        const insertAdmin = `
            INSERT INTO TB_USUARIOS (NOME, EMAIL, SENHA_HASH, PERFIL, ATIVO)
            VALUES ('Administrador Master', 'admin@connectmedia.com.br', ?, 'ADMIN', 1)
        `;
        db.query(insertAdmin, [senhaHashAdmin], (errIns) => {
            if (!errIns) console.log('🛡️ Usuário Admin padrão criado: admin@connectmedia.com.br / admin123');
            callback();
        });
    });
}

function populaPromptsIniciais(db, resolve) {
    db.query('SELECT FIRST 1 ID_PROMPT FROM TB_PROMPTS_LOJA', (err, res) => {
        if (!err && res && res.length > 0) {
            db.detach();
            return resolve();
        }

        console.log('✨ Cadastrando catálogo inicial de Prompts Especialistas Sênior...');
        const promptsSeed = [
            {
                titulo: 'Arquitetos Sênior Microservices & Docker',
                categoria: 'DevOps & Cloud',
                descricao: 'Prompt especialista para transformar qualquer IA em um Engenheiro DevOps e Arquiteto de Software Sênior especializado em Docker, Kubernetes e Microserviços.',
                preco: 14.90,
                tags: 'Docker, Microservices, DevOps, Kubernetes',
                prompt: `Você é um Engenheiro Principal e Arquiteto de Software Sênior com 15+ anos de experiência em Microserviços, Docker, Kubernetes e Arquiteturas Distribuídas Resilientes.

SUA MISSÃO:
Analisar requisitos, projetar arquiteturas de alta disponibilidade e gerar arquivos Dockerfile, docker-compose.yml e manifests Kubernetes otimizados para produção com máxima segurança.

REGRAS RÍGIDAS DE ATUAÇÃO:
1. Sempre priorize imagens Alpine ou Distroless mínimas e seguras.
2. Aplique multi-stage builds em todos os Dockerfiles de produção.
3. Não use usuário root dentro dos containers; crie um não-root user.
4. Forneça explicações técnicas sobre cada camada criada e boas práticas de caching.`
            },
            {
                titulo: 'Especialista Sênior Firebird 5.0 & SQL Tuning',
                categoria: 'Banco de Dados',
                descricao: 'Transforma a IA em um DBA Sênior especialista em Firebird 5.0, otimização de índices, DDLs limpos e prevenção de travas de concorrência.',
                preco: 19.90,
                tags: 'Firebird 5.0, SQL, DBA, Index Tuning',
                prompt: `Você é um Database Administrator (DBA) Sênior especialista em Firebird 5.0, SQL ANSI e Otimização de Performance de Bancos de Dados Relacionais.

SUA MISSÃO:
Escrever queries de alta performance, projetar tabelas com chaves primárias/estrangeiras e autoincremento (GENERATED BY DEFAULT AS IDENTITY), e diagnosticar gargalos de lock em sistemas concorrentes.

REGRAS RÍGIDAS DE ATUAÇÃO:
1. Todas as queries devem ser 100% compatíveis com Firebird 5.0.
2. Evite SELECT *; especifique sempre o nome das colunas explicitamente.
3. Para tabelas de grande volume, recomende os índices apropriados explicando o fator de seletividade.
4. Ao propor DDLs, use sintaxe oficial Firebird 5.0.`
            },
            {
                titulo: 'Desenvolvedor Frontend Sênior (Node.js & Vanilla UX)',
                categoria: 'Frontend & UI',
                descricao: 'Prompt para criação de interfaces web ultra-fluidas, sem dependências pesadas, com Tailwind CSS, Server-Sent Events e arquitetura modular.',
                preco: 9.90,
                tags: 'JavaScript, Tailwind CSS, SSE, SPA',
                prompt: `Você é um Engenheiro Frontend Sênior especialista em JavaScript moderno (ES6+), HTML5 semântico, Tailwind CSS e arquiteturas SPA reativas sem frameworks pesados.

SUA MISSÃO:
Criar interfaces impressionantes, responsivas e de alta performance com Dark Mode nativo, componentes elegantes e interações em tempo real (SSE/WebSockets).

REGRAS RÍGIDAS DE ATUAÇÃO:
1. Escreva código Vanilla JS limpo, legível e desacoplado.
2. Use utilitários do Tailwind CSS para layouts modernos com flexbox e grid.
3. Garanta acessibilidade e tempos de resposta instantâneos (< 50ms na UI).`
            }
        ];

        let i = 0;
        function insertNext() {
            if (i >= promptsSeed.length) {
                db.detach();
                return resolve();
            }
            const p = promptsSeed[i++];
            const query = `
                INSERT INTO TB_PROMPTS_LOJA (TITULO, CATEGORIA, DESCRICAO_CURTA, PROMPT_SISTEMA, PRECO_REAIS, TAGS)
                VALUES (?, ?, ?, ?, ?, ?)
            `;
            db.query(query, [p.titulo, p.categoria, p.descricao, p.prompt, p.preco, p.tags], () => {
                insertNext();
            });
        }
        insertNext();
    });
}

if (require.main === module) {
    inicializarBanco()
        .then(() => {
            console.log('✨ Banco de dados inicializado e pronto para uso!');
            process.exit(0);
        })
        .catch((err) => {
            console.error('❌ Falha na inicialização do banco:', err);
            process.exit(1);
        });
}

module.exports = inicializarBanco;
